# -*- coding: utf-8 -*-
"""Barira Najam, 577187

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ibF6SbzEsIL6QZ6vmVXyTKVPgMMoblq

Operator
"""

2+9

"""Strings"""

s='hello world'
print (s)

"""Dir and Help"""

s = 'abc'
dir(s)

s = 'hello world, hello python'

s.find('hello',5)

"""lists"""

fruits = ['apple', 'banana', 'cherry', 'banana']
fruits[0]

"""tuples"""

t = (1, 2, 3)
t[0]

"""sets"""

s = {1, 2, 3}
s.add(4)
s.remove(2)
{1,2} | {2,3}

"""dictionaries"""

d = {'name': 'Alice', 'age': 30}
d['name']

"""writing scripts"""

# script.py
def greet(name):
    return f"Hello, {name}!"

print(greet("Alice"))

"""Indentation"""

if True:
    print("indented block")
    if True:
        print("nested block")

"""Tabs vs Spaces"""

# we mix tabs and spaces in the same block — causes TabError
# 4 spaces are used per indent level

def f():
    x = 1   # 4 spaces
    return x

"""Writing Functions"""

def add(a, b=10):
    return a + b

print(add(5))
print(add(5, 20))

"""Defining Classes"""

class Dog:
    def __init__(self, name):
        self.name = name

    def bark(self):
        return f"{self.name} says Woof!"

"""Using Objects"""

class Car:
    def __init__(self, brand, speed):
        self.brand = brand
        self.speed = speed

    def drive(self):
        return f"{self.brand} is driving at {self.speed} km/h"

c1 = Car("Toyota", 120)
c2 = Car("Honda", 100)

print(c1.drive())
print(c2.drive())
print(c1.brand)
c1.speed = 150
print(c1.drive())

"""Static vs Instance Variables"""

class Dog:
    species = "Canine"   # static/class variable (shared)

    def __init__(self, name):
        self.name = name  # instance variable (unique per object)

d1 = Dog("Rex")
d2 = Dog("Fido")
print(d1.species, d2.species)   # shared
print(d1.name, d2.name)          # unique

"""Tips and Tricks"""

# Swap without a temp variable
a, b = 1, 2
a, b = b, a
print(a, b)